config/routes.rb
Rails.application.routes.draw do

  get 'events/new'
  post 'events/create'
  get 'events' => 'events#index'

  resources :users, only: [:new, :create, :show]
  root 'users#new'

  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'


end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_attendings, :foreign_key => :attended_event_id
  has_many :attendees, :through => :event_attendings, :source => :event_attendee
  belongs_to :creator, :class_name => 'User'
end

app/models/event_attending.rb
class EventAttending < ActiveRecord::Base
  belongs_to :event_attendee, :class_name => 'User'
  belongs_to :attended_event, :class_name => 'Event'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :event_attendings, :foreign_key => :event_attendee_id
  has_many :attended_events, :through => :event_attendings
  has_many :created_events, :foreign_key => :creator_id, :class_name => 'Event'

  validates :name,  presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  end

  def create
    user.event.build(creator_id: user.id)
  end

  def index
    user = User.find_by(id: current_user.id)

    @events = Event.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      flash[:success] = 'Signed in'
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid name'
      render 'users/new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_reader :user
  def new
  end

  def create
    @user = User.create(user_params)
    if user.save
      flash[:success] = 'User created'
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid user'
      render 'users/new'
    end
  end

  def show
    user = User.find(params[:id])
    events = Event.all
    created_events = events.where(:creator_id => user.id)
    @events = user.attended_events
    @upcoming_events = 'Upcoming'
    @previous_events = 'Previous'
  end


end

private

def user_params
  params.require(:user).permit(:name)
end

app/helpers/application_helper.rb
module ApplicationHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
     User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?

  end

  def log_out
  current_user = nil
  session[:user_id] = nil

  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h4>All events</h4>
<% events = @events.each do |event| %>
<%= event.id %>
<% end %>
<h4>All past events</h4>
<% events = @events.each do |event| %>
<%= event.id if (event.date < Time.now) %>
<% end %>


<h4>All upcoming events</h4>

<% events = @events.each do |event| %>
<%= event.id if (event.date > Time.now) %>
<% end %>



<div>

<%= link_to 'User Page', user_path(current_user) %>
</div>

app/views/events/new.html.erb
<h3>Create event</h3>

<%= form_for(:event, url: events_create_path) do |f| %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.submit 'Sign up' %>
<% end %>

app/views/events/show.html.erb
<%= event.creator =>
<%= event.attendees =>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Private Events</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h4>
  <% if logged_in? %>
  <%= "Logged in as  #{current_user.name}" %>
  <%= link_to 'Log out', logout_path, method: 'delete' %> 
  <% end %>
</h4>
    <div class="container">
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

<%= yield %>
</div>
</body>
</html>

app/views/users/new.html.erb
<h3>Sign up</h3>

<%= form_for(:user, url: users_path) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit 'Sign up' %>
<% end %>

<h3>Have an account? Sign in</h3>

<%= form_for(:session, url: login_path) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit 'Sign in' %>
<% end %>

app/views/users/show.html.erb
This is <%= current_user.name %>'s content
<h4>All User's Events</h4>
<% @events.each do |event| %>
<%= event.id %>
<%end%>

<h4>Upcoming events</h4>
<%= @upcoming_events %>

<h4>Previous events</h4>
<%= @previous_events %>
<br>
<%= link_to 'All events', events_path %>